[package]
name = "remote-hdt"
version = "0.0.1"
edition = "2021"

[dependencies]
zarr3 = { git = "https://github.com/clbarnes/zarr3-rs.git" }
rdf-rs = { path = "./rdf-rs" }
rio_api = "0.8.4"
ndarray = { version = "0.15.6", features = [ "rayon" ] }
bimap = "0.6.3"