[package]
authors = [ "Ángel Iglesias Préstamo <angel.iglesias.prestamo@gmail.com>" ]
name = "remote-hdt"
version = "0.0.1"
edition = "2021"

[dependencies]
zarrs = { git = "https://github.com/LDeakin/zarrs.git", default-features = false}
rdf-rs = { path = "./rdf-rs" }
clap = { version = "4.1.8", features = ["derive"] }
serde_json = "1.0.108"
rayon = "1.8.0"
thiserror = "1.0.50"
nalgebra-sparse = "0.9.0"

[profile.release]
codegen-units = 1
opt-level = 3
lto = "thin"